Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"
  config.vm.define "box1" do |box1|
    box1.vm.network "private_network", ip: "192.168.56.13"
    box1.vm.hostname = "box1"
  end
end
