Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/8"

  config.vm.define "squid1" do |squid1|
    squid1.vm.network "private_network", ip: "192.168.56.21"
    squid1.vm.network "public_network", ip: "192.168.1.248", bridge: "en3: Thunderbolt Ethernet"
    squid1.vm.hostname = "squid1"
    squid1.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.56.13"
    jenkins.vm.network "public_network", ip: "192.168.1.238", bridge: "en3: Thunderbolt Ethernet"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "agent1" do |agent1|
    agent1.vm.network "private_network", ip: "192.168.56.15"
    agent1.vm.hostname = "agent1"
    agent1.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end
end
