Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/8"

  config.vm.define "weekly" do |weekly|
    weekly.vm.network "private_network", ip: "192.168.56.13"
    # weekly.vm.network "public_network", ip: "192.168.1.85"
    weekly.vm.hostname = "weekly"
    weekly.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 2048
    end
  end
end
