Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.9"

  config.vm.define "jenkinsold" do |jenkinsold|
    jenkinsold.vm.network "private_network", ip: "192.168.32.13"
    jenkinsold.vm.hostname = "jenkinsold"
    jenkinsold.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "jenkinsnew" do |jenkinsnew|
    jenkinsnew.vm.network "private_network", ip: "192.168.32.16"
    jenkinsnew.vm.hostname = "jenkinsnew"
    jenkinsnew.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

end
