---
- name: Install base software on all
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: update hosts
      lineinfile:
        path: "/etc/hosts"
        regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        line: "{{ hostvars[item]['ansible_ssh_host'] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        state: present
        backup: true
      with_items: "{{ ansible_play_batch }}"       
    - name: Adoptium yum repository
      yum_repository:
        name: Adoptium
        description: Adoptium
        baseurl: https://packages.adoptium.net/artifactory/rpm/rocky/$releasever/$basearch
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.adoptium.net/artifactory/api/gpg/key/public
    - name: Endpoint yum repository
      yum_repository:
        name: endpoint
        description: End Point repository
        baseurl: https://packages.endpointdev.com/rhel/$releasever/os/$basearch/
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.endpointdev.com/endpoint-rpmsign-7.pub
    - name: remove any installed git
      yum:
        name: git
        state: absent
    - name: Install fontconfig, AdoptOpenJDK and git
      yum:
        name:
          - temurin-11-jdk
          - git
          - wget
          - epel-release
          - unzip
          - ntp
          - ntpdate
        state: latest
    - name: enable ntpd
      systemd:
        name: ntpd
        state: restarted
        enabled: true    
      
- name: Jenkins installation
  hosts: jenkins_controllers
  become: true
  tasks:
    - name: enable and start firewalld service
      systemd:
        name: firewalld
        state: started
        enabled: true
    - name: permit traffic in default zone on port 8080/tcp
      ansible.posix.firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: true
    - name: permit traffic in default zone on port 50000/tcp
      ansible.posix.firewalld:
        port: 50000/tcp
        permanent: true
        state: enabled
        immediate: true
    - name: jenkins yum repository
      yum_repository:
        name: jenkins
        description: Jenkins-stable
        baseurl: http://pkg.jenkins.io/redhat-stable
        enabled: true
        gpgcheck: true
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: Install Jenkins
      yum:
        name:
          - jenkins-2.332.3
        state: latest
    - name: Create directories for Jenkins
      file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
        recurse: true
      with_items:
        - '/var/cache/jenkins/tmp'
        - '/var/cache/jenkins/heapdumps'
    - name: Create directory for systemd override file
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        recurse: true
      with_items:
        - '/etc/systemd/system/jenkins.service.d'
    - name: Create limits file
      copy:
        dest: "/etc/systemd/system/jenkins.service.d/override.conf"
        src: "override.conf"
    - name: start jenkins service
      systemd:
        name: jenkins
        state: restarted

- name: Agent installation
  hosts: agents
  become: true
  tasks:
    - name: enable and start firewalld service
      systemd:
        name: firewalld
        state: started
        enabled: true
    - name: permit traffic in default zone on port 22/tcp
      ansible.posix.firewalld:
        port: 22/tcp
        permanent: true
        state: enabled
        immediate: true
    - name: Install Docker and unzip
      yum:
        name: 
          - unzip
          - gcc
          - zlib-devel
        state: latest
    - name: create GraalVM directory
      file: 
        path: "/opt/tools/graalvm"
        state: directory
        owner: vagrant
        group: vagrant
        recurse: true
    - name: download GraalVM 22.1.0
      unarchive:
        src: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java17-linux-amd64-22.1.0.tar.gz
        dest: /opt/tools/graalvm
        remote_src: true
    - name: setup GraalVM profile
      copy:
        dest: /etc/profile.d/graalvm.sh
        content: |
          PATH=/opt/tools/graalvm/graalvm-ce-java17-22.1.0/bin:$PATH
          JAVA_HOME=/opt/tools/graalvm
    - name: create jreleaser directory
      file: 
        path: "/opt/tools/jreleaser"
        state: directory
        owner: vagrant
        group: vagrant
        recurse: true
    - name: download jreleaser 1.0.0
      unarchive:
        src: https://github.com/jreleaser/jreleaser/releases/download/v1.0.0/jreleaser-1.0.0.zip
        dest: /opt/tools/jreleaser
        remote_src: true
    - name: setup JReleaser profile
      copy:
        dest: /etc/profile.d/jreleaser.sh
        content: |
          PATH=/opt/tools/jreleaser/jreleaser-1.0.0/bin:$PATH
    - name: set final ownership to /opt/tools
      file: 
        path: "/opt/tools"
        state: directory
        owner: vagrant
        group: vagrant
        recurse: true        