---
- name: Install base software on all
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: update hosts
      lineinfile:
        path: "/etc/hosts"
        regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        line: "{{ hostvars[item]['ansible_ssh_host'] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        state: present
        backup: true
      with_items: "{{ ansible_play_batch }}"       
    - name: Adoptium yum repository
      yum_repository:
        name: Adoptium
        description: Adoptium
        baseurl: https://packages.adoptium.net/artifactory/rpm/rocky/$releasever/$basearch
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.adoptium.net/artifactory/api/gpg/key/public
    - name: remove any installed git
      dnf:
        name: git
        state: absent
    - name: Install temurin and git
      dnf:
        name:
          - temurin-21-jdk
          - git
          - wget
          - net-tools
          - setools-console
          - policycoreutils-python-utils
        state: latest
      
- name: Jenkins installation
  hosts: jenkins_controllers
  become: true
  tasks:
    - name: enable and start firewalld service
      ansible.builtin.systemd_service:
        name: firewalld
        state: stopped
        enabled: true
    - name: jenkins yum repository
      yum_repository:
        name: jenkins
        description: Jenkins-stable
        baseurl: http://pkg.jenkins.io/redhat-stable
        enabled: true
        gpgcheck: true
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    - name: Install Jenkins
      dnf:
        name:
          - jenkins-2.479.3
          - httpd
          - httpd-tools
        state: latest
    - name: Create directories for Jenkins
      file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
        recurse: true
      with_items:
        - '/var/cache/jenkins/tmp'
        - '/var/cache/jenkins/heapdumps'
    - name: Create directory for systemd override file
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        recurse: true
      with_items:
        - '/etc/systemd/system/jenkins.service.d'
    - name: Create limits file
      copy:
        dest: "/etc/systemd/system/jenkins.service.d/override.conf"
        src: "override.conf"
    - name: restart jenkins service
      systemd:
        name: jenkins
        state: restarted
        enabled: true
    - name: restart httpd service
      systemd:
        name: httpd
        state: restarted
        enabled: true