Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/8"

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.56.13"
    jenkins.vm.network "public_network", ip: "192.168.1.238", bridge: "en3: Thunderbolt Ethernet"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 2048
    end
  end

  config.vm.define "agent1" do |agent1|
    agent1.vm.network "private_network", ip: "192.168.56.15"
    agent1.vm.network "public_network", ip: "192.168.1.240", bridge: "en3: Thunderbolt Ethernet"
    agent1.vm.disk :disk, size: "40GB", primary: true
    agent1.vm.hostname = "agent1"
    agent1.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 2048
    end
    agent1.vm.provision "shell", inline: <<-SHELL
      printf "\nDisk free space before...\n"
      df -lhT /

      printf "\nResizing / partition live with sgdisk...\n"
      dnf install -y gdisk
      sgdisk -g -e /dev/sda
      sgdisk -d 1 /dev/sda
      sgdisk -N 1 /dev/sda
      partprobe /dev/sda
      xfs_growfs /dev/sda1

      printf "\nDisk free space after...\n"
      df -lhT /    
    SHELL
  end
end