Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.9"

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.32.13"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider :virtualbox do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "jenkinslts" do |jenkinslts|
    jenkinslts.vm.network "private_network", ip: "192.168.32.16"
    jenkinslts.vm.hostname = "jenkinslts"
    jenkinslts.vm.provider :virtualbox do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

end
