Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/8"

  config.vm.define "gitea" do |gitea|
    gitea.vm.network "private_network", ip: "192.168.56.21"
    gitea.vm.network "public_network", ip: "192.168.1.247"
    gitea.vm.hostname = "gitea"
    gitea.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end
end
