Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/8"

  config.vm.define "jenkinsold" do |jenkinsold|
    jenkinsold.vm.network "private_network", ip: "192.168.56.13"
    jenkinsold.vm.network "public_network", ip: "192.168.1.246", bridge: "en3: Thunderbolt Ethernet"
    jenkinsold.vm.hostname = "jenkinsold"
    jenkinsold.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "jenkinsnew" do |jenkinsnew|
    jenkinsnew.vm.network "private_network", ip: "192.168.56.16"
    jenkinsnew.vm.network "public_network", ip: "192.168.1.247", bridge: "en3: Thunderbolt Ethernet"
    jenkinsnew.vm.hostname = "jenkinsnew"
    jenkinsnew.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

end
