---
- name: Install base software on all
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: update hosts
      lineinfile:
        path: "/etc/hosts"
        regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        line: "{{ hostvars[item]['ansible_ssh_host'] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        state: present
        backup: true
      with_items: "{{ ansible_play_batch }}"       
    - name: Install gpg
      apt:
        name:
          - wget
          - gpg
          - apt-transport-https 
        state: latest
        update_cache: yes
    - name: add Adoptium apt key
      ansible.builtin.apt_key:
        url: https://packages.adoptium.net/artifactory/api/gpg/key/public
        state: present
    - name: add Adoptium repository
      ansible.builtin.apt_repository:
        repo: deb https://packages.adoptium.net/artifactory/deb focal main
        state: present
    - name: Install common software
      apt:
        name:
          - temurin-21-jdk
          - ca-certificates 
          - curl 
          - git
          - software-properties-common
          - unzip
          - ufw
        state: latest
        update_cache: yes
      
- name: Jenkins installation
  hosts: jenkins_controllers
  become: true
  tasks:
    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
    - name: Allow all access to tcp port 8080
      community.general.ufw:
        rule: allow
        port: '8080'
        proto: tcp
    - name: Allow all access to tcp port 80
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
    - name: Allow all access to tcp port 443
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp
    - name: Allow all access to tcp port 22
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp
    - name: add Jenkins apt key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present
    - name: Jenkins deb repository
      ansible.builtin.apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present
    - name: Install Jenkins and nginx
      apt:
        name:
          - jenkins=2.479.1
          - nginx
          - libnginx-mod-http-brotli-filter
          - libnginx-mod-http-brotli-static
        update_cache: yes
    - name: Stop Jenkins (autostarts after install)
      systemd:
        name: jenkins
        state: stopped
    - name: delete JENKINS_HOME directory
      file:
        state: absent
        path: /var/lib/jenkins
    - name: Create directories for Jenkins
      file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
        recurse: true
      with_items:
        - '/var/cache/jenkins/tmp'
        - '/var/cache/jenkins/heapdumps'
        - '/var/lib/jenkins'
    - name: Create directory for systemd override file
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        recurse: true
      with_items:
        - '/etc/systemd/system/jenkins.service.d'
    - name: Create limits file
      copy:
        dest: "/etc/systemd/system/jenkins.service.d/override.conf"
        src: "override.conf"
    - name: Create nginx file
      copy:
        dest: "/etc/nginx/conf.d/jenkins.conf"
        src: "jenkins.conf"
    - name: create ssl directory
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0755'
    - name: Create SSL private key
      copy:
        dest: "/etc/nginx/ssl/privkey.pem"
        src: "privkey.pem"
        mode: '0600'
    - name: Create SSL certificate
      copy:
        dest: "/etc/nginx/ssl/fullchain.pem"
        src: "fullchain.pem"
        mode: '0644'
    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent        
    - name: start jenkins service
      systemd:
        name: jenkins
        state: restarted
        enabled: true
    - name: start nginx service
      systemd:
        name: nginx
        state: restarted
        enabled: true        