Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/8"
  config.disksize.size='40GB'

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.56.13"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 3072
    end
  end
end
