Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/8"

  config.vm.define "k3sm" do |k3sm|
    k3sm.vm.network "private_network", ip: "192.168.56.20"
    k3sm.vm.hostname = "k3sm"
    k3sm.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 2048
    end
  end
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.56.13"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

end
