---
- name: Install base software on all
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: update hosts
      lineinfile:
        path: "/etc/hosts"
        regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        line: "{{ hostvars[item]['ansible_ssh_host'] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        state: present
        backup: true
      with_items: "{{ ansible_play_batch }}"       
    - name: Adoptium yum repository
      yum_repository:
        name: Adoptium
        description: Adoptium
        baseurl: https://packages.adoptium.net/artifactory/rpm/rocky/$releasever/$basearch
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.adoptium.net/artifactory/api/gpg/key/public
    - name: remove any installed git
      yum:
        name: git
        state: absent
    - name: Install
      yum:
        name:
          - temurin-21-jdk
          - git
          - wget
          - epel-release
          - unzip
        state: latest
      
- name: Jenkins installation
  hosts: jenkins_controllers
  become: true
  tasks:
    - name: enable and start firewalld service
      systemd:
        name: firewalld
        state: started
        enabled: true
    - name: permit traffic in default zone on port 8080/tcp
      ansible.posix.firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: true
    - name: permit traffic in default zone on port 50000/tcp
      ansible.posix.firewalld:
        port: 50000/tcp
        permanent: true
        state: enabled
        immediate: true
    - name: jenkins yum repository
      yum_repository:
        name: jenkins
        description: Jenkins-stable
        baseurl: http://pkg.jenkins.io/redhat-stable
        enabled: true
        gpgcheck: true
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: Install Jenkins
      yum:
        name:
          - jenkins-2.479.3
        state: latest
    - name: Create directories for Jenkins
      file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
        recurse: true
      with_items:
        - '/var/cache/jenkins/tmp'
        - '/var/cache/jenkins/heapdumps'
    - name: Create directory for systemd override file
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        recurse: true
      with_items:
        - '/etc/systemd/system/jenkins.service.d'
    - name: Create limits file
      copy:
        dest: "/etc/systemd/system/jenkins.service.d/override.conf"
        src: "override.conf"
    - name: start jenkins service
      systemd:
        name: jenkins
        state: restarted

- name: Agent installation
  hosts: agents
  become: true
  tasks:
    - name: enable and start firewalld service
      systemd:
        name: firewalld
        state: started
        enabled: true
    - name: permit traffic in default zone on port 22/tcp
      ansible.posix.firewalld:
        port: 22/tcp
        permanent: true
        state: enabled
        immediate: true
    - name: remove any installed docker
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent
    - name: docker-ce-stable yum repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/8/$basearch/stable
        enabled: true
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/centos/gpg
    - name: Install Docker and unzip
      yum:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - unzip
          - tree
          - gcc
          - zlib-devel
        state: latest
    - name: add docker group
      group:
        name: docker
        state: present
    - name: add $USER to docker group
      user: 
        name: "{{ ansible_user }}"
        groups: docker
        append: true
    - name: do a ssh reset in order to reflect the $USER group changes
      meta: reset_connection
    - name: start Docker service
      systemd:
        name: docker
        state: restarted        
    - name: create fly directory
      file: 
        path: "/opt/tools/fly"
        state: directory
        owner: vagrant
        group: vagrant
        recurse: true
    - name: download flyctl
      unarchive:
        src: https://github.com/superfly/flyctl/releases/download/v0.0.498/flyctl_0.0.498_Linux_x86_64.tar.gz
        dest: /opt/tools/fly
        remote_src: true
    - name: setup fly profile
      copy:
        dest: /etc/profile.d/fly.sh
        content: |
          PATH=/opt/tools/fly:$PATH
    - name: create Trivy directory
      file: 
        path: "/opt/tools/trivy"
        state: directory
        owner: vagrant
        group: vagrant
        recurse: true
    - name: download Trivy
      unarchive:
        src: https://github.com/aquasecurity/trivy/releases/download/v0.38.3/trivy_0.38.3_Linux-64bit.tar.gz
        dest: /opt/tools/trivy
        remote_src: true
    - name: setup Trivy profile
      copy:
        dest: /etc/profile.d/trivy.sh
        content: |
          PATH=/opt/tools/trivy:$PATH
    - name: create Grype directory
      file: 
        path: "/opt/tools/grype"
        state: directory
        owner: vagrant
        group: vagrant
        recurse: true
    - name: download Grype
      unarchive:
        src: https://github.com/anchore/grype/releases/download/v0.59.1/grype_0.59.1_linux_amd64.tar.gz
        dest: /opt/tools/grype
        remote_src: true
    - name: setup Grype profile
      copy:
        dest: /etc/profile.d/grype.sh
        content: |
          PATH=/opt/tools/grype:$PATH
    - name: set final ownership to /opt/tools
      file: 
        path: "/opt/tools"
        state: directory
        owner: vagrant
        group: vagrant
        recurse: true