Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.9"

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.32.13"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "jenkins" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "nexus" do |nexus|
    nexus.vm.network "private_network", ip: "192.168.32.11"
    nexus.vm.hostname = "nexus"
    nexus.vm.provider "nexus" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end
end
