Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/8"

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.56.13"
    jenkins.vm.network "public_network", ip: "192.168.1.242", bridge: "en3: Thunderbolt Ethernet"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 2048
    end
  end

end