Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.9"

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.32.15"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider :virtualbox do |vb|
      vb.cpus = 1
      vb.memory = 8192
    end
  end

end
