Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.56.13"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--vram", "12"]
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
      vb.cpus = 1
      vb.memory = 1024
    end
  end

end
